SELECT * 
	,CASE 
		WHEN max(CASE WHEN DNA_ACTION IS NOT NULL AND DNA_ACTION IN ('DNA') THEN 1 ELSE 0 end) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) = 1 THEN 'DNA'
		WHEN max(CASE WHEN PVN_CLAIM_NUMBER IS NOT NULL THEN 1 ELSE 0 END ) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) =1 THEN 'PROFECTUS CLAIMED'
		WHEN ELIGIBLE IS NULL THEN 'ELIGIBLE NULL'
		WHEN SUM({0}) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) < 300 THEN '{0} < 300'
		ELSE  concat('TO QA_',ifnull(DNA_ACTION,''))
	end	CHECK_COLUMN
FROM coles.STI_WIP_CO.{1}
WHERE to_char(PROMO_END_DT,'YYYYMM') = '{2}'
ORDER BY SUPP_IDNT,DEPT_IDNT,ITEM_IDNT_VCHAR