WITH co_schema AS
(
	(SELECT DISTINCT PRMTN_COMP_IDNT PROMO_ID,SUPP_IDNT SUPPLIER_ID , DEPT_IDNT CAT_NUM, 'ONLINE' CLASSIFY_NOTE, PROMO_START_DT , PROMO_END_DT 
		,CASE 
			WHEN max(CASE WHEN DNA_ACTION IS NOT NULL AND DNA_ACTION IN ('DNA') THEN 1 ELSE 0 end) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) = 1 THEN 'DNA'
			WHEN max(CASE WHEN PVN_CLAIM_NUMBER IS NOT NULL THEN 1 ELSE 0 END ) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) =1 THEN 'PROFECTUS CLAIMED'
			WHEN ELIGIBLE_2 IS NULL THEN 'ELIGIBLE_2 IS NULL'
			WHEN SUM(ELIGIBLE_2) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) < 300 THEN 'ELIGIBLE_2 < 300'
			ELSE  concat('TO QA_',ifnull(DNA_ACTION,''))
		end	CHECK_COLUMN
	FROM coles.STI_WIP_CO.VIEW_MULTIBUYPROMOS_COLOTHER_SCHEMA 
	QUALIFY CHECK_COLUMN ILIKE '%QA%')
	UNION ALL 
	(SELECT DISTINCT PRMTN_COMP_IDNT PROMO_ID,SUPP_IDNT SUPPLIER_ID , DEPT_IDNT CAT_NUM, 'ONLINE MULTIBUYS EXCLUSIVE' CLASSIFY_NOTE, PROMO_START_DT , PROMO_END_DT 
		,CASE 
			WHEN max(CASE WHEN DNA_ACTION IS NOT NULL AND DNA_ACTION IN ('DNA') THEN 1 ELSE 0 end) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) = 1 THEN 'DNA'
			WHEN max(CASE WHEN PVN_CLAIM_NUMBER IS NOT NULL THEN 1 ELSE 0 END ) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) =1 THEN 'PROFECTUS CLAIMED'
			WHEN ELIGIBLE IS NULL THEN 'ELIGIBLE IS NULL'
			WHEN SUM(ELIGIBLE) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) < 300 THEN 'ELIGIBLE < 300'
			ELSE  concat('TO QA_',ifnull(DNA_ACTION,''))
		end	CHECK_COLUMN
	FROM coles.STI_WIP_CO.VIEW_CO_EXC_TH_SCHEMA 
	QUALIFY CHECK_COLUMN ILIKE '%QA%')
	UNION ALL 
	(SELECT DISTINCT PRMTN_COMP_IDNT PROMO_ID,SUPP_IDNT SUPPLIER_ID , DEPT_IDNT CAT_NUM, 'ONLINE SIMPLE EXCLUSIVE' CLASSIFY_NOTE, PROMO_START_DT , PROMO_END_DT 
		,CASE 
			WHEN max(CASE WHEN DNA_ACTION IS NOT NULL AND DNA_ACTION IN ('DNA') THEN 1 ELSE 0 end) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) = 1 THEN 'DNA'
			WHEN max(CASE WHEN PVN_CLAIM_NUMBER IS NOT NULL THEN 1 ELSE 0 END ) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) =1 THEN 'PROFECTUS CLAIMED'
			WHEN ELIGIBLE IS NULL THEN 'ELIGIBLE IS NULL'
			WHEN SUM(ELIGIBLE) OVER (PARTITION BY prmtn_comp_idnt, SUPP_IDNT, dept_idnt) < 300 THEN 'ELIGIBLE < 300'
			ELSE  concat('TO QA_',ifnull(DNA_ACTION,''))
		end	CHECK_COLUMN
	FROM coles.STI_WIP_CO.VIEW_CO_EXC_SIMP_SCHEMA 
	QUALIFY CHECK_COLUMN ILIKE '%QA%')
)
SELECT * 
FROM co_schema
WHERE to_char(PROMO_END_DT,'YYYYMM') = '{}'
-- AND PROMO_ID = '55201937'
ORDER BY SUPPLIER_ID,CAT_NUM,PROMO_END_DT