SELECT CML_COST_GST_RATE_PCT, dept_idnt,SUPPLIER SUPP_IDNT,SUPPLIER_NAME SUPP_DESC, SAP_ID VENDOR_NUM 
FROM COLES.STI_WIP_CS.PRODUCT_VENDOR
WHERE sku_id  IN ('{}')
AND SUPPLIER != '-1'
AND '{}' BETWEEN MIN_DAY AND MAX_DAY
GROUP BY CML_COST_GST_RATE_PCT, dept_idnt,SUPPLIER ,SUPPLIER_NAME , SAP_ID  
ORDER BY sum(TOTAL_SALES_QTY) DESC
-- LIMIT 1