SELECT ITEM_IDNT_VCHAR, ITEM_LONG_DESC , CLM_REF_NUM, CLAIM_RATE, CLAIM_QTY, CLAIM_AMT
FROM {0}
WHERE PRMTN_COMP_IDNT = '{1}'
AND SUPP_IDNT = '{2}'
AND DEPT_IDNT  = '{3}'
AND PICKED_QTY != 0
ORDER BY ITEM_IDNT_VCHAR
;