SELECT *
FROM COLES.AUDIT_ETC.TBL_DEAL_DETAIL_ALL a 
WHERE DR_ID ILIKE '%COLS%' AND RMS_DEAL_ID IS NOT NULL AND DEAL_TYPE NOT LIKE '%Straight Monies%' AND CLAIM_STATUS='Submitted'
AND CLM_REF_NUM IN ('{0}')
;