SELECT DISTINCT {4}
FROM {0}
WHERE PRMTN_COMP_IDNT = '{1}'
AND SUPP_IDNT = '{2}'
AND DEPT_IDNT  = '{3}'
QUALIFY sum(PICKED_QTY) OVER (PARTITION BY ITEM_IDNT) > 0
ORDER BY ORDER_STAGING_DAY_IDNT , ITEM_IDNT_VCHAR , STATE ;