SELECT *
--  CLASSIFY_CLAIM, CLASSIFY_STATE, VENDOR_NUMBER, VENDOR_NAME, BRANDID, ITEMID, ITEMNAME, MULTIPLIER_NUM, REBATE_ENTITLEMENT_NUM,
--  STARTDATE :: DATE STARTDATE
--  , ENDDATE :: DATE ENDDATE
--   , PAF_LINK, EMAIL, CLM_QTY, PROMOPRICE_EXC, CLASSIFY_TYPE, ACT_PRICE_EXC, SLS_QTY, YEAR_CLM, NORMAL_PRICE_EXC, ITEMCOGS, SCAN_RATE_SUGGEST, PROMO_PRICE_SUGGEST, PRICE_ACTUAL_LESS_THAN_PROMO_EXC, PROMO_QTY, PROMO_AMT, SUM_AMT_GAP, ITEMGROUP, CATEGORY_ID, PAF_LINK_SUGGEST, EMAIL_SUGGEST
 , CASE WHEN SUM_AMT_GAP <= 20000 THEN '_LESSTHAN20K' ELSE '' END CLASSIFY_AMOUNT
FROM COLES.LIQUORLAND.CT_CL_GAP_AMT
WHERE  
enddate between  '2022-4-1' and   '2022-4-15'
-- and itemid in ('3276085','3222610') AND brandid = '1C'
-- startdate = '2021-5-5' and enddate = '2021-6-1' 
-- -- and 
-- and 
-- vendor_number in ('972410')
-- and itemid = '3581792'

