SELECT listagg(DISTINCT concat(ITEM_ID,' ',START_DTE,' ',END_DTE),', ') over() ITEM_RAISED ,listagg(DISTINCT CLAIM_NUM,', ') over() CLAIM_PROF, FILE_PATH 
from
(
SELECT DISTINCT ITEM_ID,START_DTE,END_DTE , CLAIM_NUM,FILE_PATH
FROM COLES.PVN_CLAIMS.CT_CL_DETAIL_SCAN
WHERE 
AGREED_SCAN_RATE = {0}
AND ITEM_ID in ('{1}')
AND BRAND = '{4}'
AND UOM = '{5}'
AND (START_DTE BETWEEN '{2}'::DATE AND '{3}'::DATE OR END_DTE BETWEEN '{6}'::DATE  AND '{7}'::DATE )
AND STATE IN ({8}))
LIMIT 1
