SELECT  ITEMIDSKU, mode(accountnumber) ven_id, mode(VENDOR_NAME2) ven_name
FROM COLES.LIQUORLAND.VENDOR_FROM_SALES a 
LEFT JOIN COLES_CLEAN.LIQUORLAND_MERCH.all_dimvendor b 
	ON a.DIMVENDORID = b.DIMVENDORID
WHERE ITEMIDSKU  IN ('{}')
GROUP BY ITEMIDSKU