select DATE1, ITEMIDSKU, ITEMNAME, BRANDID, UOM_QTY, STATE, CH_VAL_EX, ITEMPRICE_EX, TOTALLINESALE_EX, ITEMQUANTITY, AGV_SALE_PRICE, ITEMQUANTITY_NON, AGV_SALE_PRICE_NON, TOTALLINESALE_EX_PROMO, ITEMQUANTITY_PROMO, AGV_SALE_PRICE_PROMO, {} scan_rate
from 
(SELECT * FROM TABLE (COLES.LIQUORLAND.CT_SUMMARIZER_CL_MULTIITEM_1(ARRAY_CONSTRUCT({}),'{}','{}', STRTOK_TO_ARRAY('{}',','), STRTOK_TO_ARRAY('{}',','), {}+0.01)))
where ITEMQUANTITY_PROMO != 0
order by brandid, ITEMIDSKU,UOM_QTY,DATE1, STATE

