SELECT listagg(DISTINCT concat(ITEM_ID,' ',START_DTE,' ',END_DTE),', ') over() ITEM_RAISED ,listagg(DISTINCT CLAIM_NUM,', ') over() CLAIM_PROF, FILE_PATH 
from
(
SELECT DISTINCT ITEM_ID,START_DTE,END_DTE , CLAIM_NUM,FILE_PATH
FROM COLES.PVN_CLAIMS.CT_CL_DETAIL_SCAN
WHERE 
AGREED_SCAN_RATE = {}
AND ITEM_ID in ('{}')
AND START_DTE BETWEEN '{}'::DATE AND '{}'::DATE 
AND BRAND = '{}'
AND UOM = '{}'
AND END_DTE BETWEEN '{}'::DATE  AND '{}'::DATE 
AND STATE IN ('{}'))
LIMIT 1
