SELECT DATE1, ITEMIDSKU, ITEMNAME, BRANDID, UOM_QTY, STATE, CH_VAL_EX, ITEMPRICE_EX, TOTALLINESALE_EX, CAST(ITEMQUANTITY AS int)  ITEMQUANTITY, AGV_SALE_PRICE, CAST(ITEMQUANTITY_NON AS int) ITEMQUANTITY_NON, AGV_SALE_PRICE_NON, TOTALLINESALE_EX_PROMO, CAST(ITEMQUANTITY_PROMO AS int) ITEMQUANTITY_PROMO, AGV_SALE_PRICE_PROMO, 
{} SCAN
FROM TABLE (COLES.LIQUORLAND.CT_SUMMARIZER_CL_20221031_NATIONAL_AUTO('{}', '{}' , '{}', '{}', {}, {}+0.2::NUMBER(38,2))) 
------------------------------------------------------------------ITEM-- START-END--BRAND-UOM---RRP-------------
order by brandid, ITEMIDSKU , UOM_QTY , DATE1