SELECT DISTINCT GST CML_COST_GST_RATE_PCT , concat(DEPT,'E') DEPT_IDNT, COLESSUPPNO SUPP_IDNT, COLESSUPPLIERNAME SUPP_DESC, SUPPID VENDOR_NUM
FROM COLES.STI_WIP_CE.ITEMLIST_CLEAN
WHERE BARCODE IN ('{}')
AND GST IS NOT NULL 
LIMIT 1
